### ISSUE TITLE
Zeus crashes on start

### ISSUE THREAD

**Issue by dnasseri** [burke/zeus#534] opened 2015-11-10 16:37 UTC
Using 
zeus v0.15.4
rvm 1.26.11
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

When I try to run Zeus Start, the following happens:

![screen shot 2015-11-10 at 11 33 04 am](https://cloud.githubusercontent.com/assets/8558194/11068426/33b0dc0e-879f-11e5-945f-0d65a237491a.png)

When I run zeus s to see backtrace I get the following

```
/Users/DN/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/parser.rb:33:in `<class:Parser>': superclass mismatch for class Mark (TypeError)
    from /Users/DN/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/parser.rb:32:in `<module:Psych>'
    from /Users/DN/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych/parser.rb:1:in `<top (required)>'
    from /Users/DN/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:7:in `require'
    from /Users/DN/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/psych.rb:7:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/activesupport-3.2.22/lib/active_support/ordered_hash.rb:2:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/activesupport-3.2.22/lib/active_support/ordered_hash.rb:2:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/activesupport-3.2.22/lib/active_support/ordered_options.rb:1:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/activesupport-3.2.22/lib/active_support/ordered_options.rb:1:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/configuration.rb:2:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/configuration.rb:2:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/railtie.rb:2:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/railtie.rb:2:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/engine.rb:1:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/engine.rb:1:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/plugin.rb:1:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/plugin.rb:1:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/application.rb:3:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/application.rb:3:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails.rb:10:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails.rb:10:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/all.rb:1:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/railties-3.2.22/lib/rails/all.rb:1:in `<top (required)>'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus/rails.rb:92:in `require'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus/rails.rb:92:in `block in boot'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus/rails.rb:91:in `each'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus/rails.rb:91:in `boot'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus.rb:200:in `run_action'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus.rb:74:in `block (2 levels) in boot_steps'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:7:in `features_loaded_by'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus.rb:73:in `block in boot_steps'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus.rb:56:in `catch'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus.rb:56:in `boot_steps'
    from /Users/DN/.rvm/gems/ruby-2.2.2@viewthespace/gems/zeus-0.15.4/lib/zeus.rb:48:in `go'
    from -e:1:in `<main>'
```

I've been trying to figure this out for a while. Any help would be greatly appreciated.

**Comment by kgrz** [comment] 2015-11-24 14:30
Just a hunch, but can you check what YAML versions zeus and the rails app are loading? You can check the version used by Rails by running `rails console` (without zeus) and checking `puts YAML::VERSION`. The global ruby version of YAML can be obtained by checking `gem list psych` using the same version that was used to install/run zeus.

**Comment by dnasseri** [comment] 2015-11-27 17:42
@kgrz the version used by rails is 2.0.8

Running `gem list psych` in the same directory lists two versions. Here is the output: 

*** LOCAL GEMS ***

psych (2.0.15, 2.0.8)

**Comment by dnasseri** [comment] 2015-11-29 13:16
uninstalling psych 2.0.15 did the trick! Thanks @kgrz !

**Comment by kgrz** [comment] 2015-11-29 13:43
🎉

**Comment by kgrz** [comment] 2015-11-30 05:33
This should be fixed by https://github.com/burke/zeus/pull/530/files

**Comment by mark-stephenson-** [comment] 2016-03-14 08:52
I'm getting the same issue, but I only have one version installed.  I have the latest version of Zeus installed and the latest version of Psych

**Comment by sideshowcoder** [comment] 2017-05-19 08:24
Since this is quite old and I can't reproduce anymore I'm gonna close this, feel free to reopen if needed.

**Closed by sideshowcoder** 2017-05-19 08:24 UTC
