### ISSUE TITLE
No such middleware

### ISSUE THREAD

**Issue by sevenmaxis** [burke/zeus#600] opened 2016-09-28 20:05 UTC
`Linux discourse 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
`

```
vagrant@discourse:/vagrant$ zeus start
Starting Zeus server v0.15.10
[ready] [crashed] [running] [connecting] [waiting]
boot
└
...
```

```
vagrant@discourse:/vagrant$ zeus console
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:125:in `assert_index': No such middleware to insert after: ActionDispatch::DebugExceptions (RuntimeError)
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:96:in `insert_after'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/configuration.rb:68:in `block in merge_into'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/configuration.rb:67:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/configuration.rb:67:in `merge_into'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/engine.rb:501:in `app'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
        from /vagrant/config/environment.rb:5:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus/rails.rb:105:in `development_environment'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus.rb:199:in `block in run_action'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus/load_tracking.rb:11:in `features_loaded_by'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus.rb:197:in `run_action'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus.rb:72:in `block in boot_steps'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus.rb:56:in `catch'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus.rb:56:in `boot_steps'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/zeus-0.15.10/lib/zeus.rb:48:in `go'
        from -e:1:in `<main>'
```

**Comment by sideshowcoder** [comment] 2017-01-10 21:29
Interesting issue, is this happening on just discourse or on multiple apps for you? It looks like there is an issue with the order of requires but this seems to be reasonably deep in the rails stack which seems odd as this seems solid in the apps I have touched so far. Would you be able to try again with the newest Zeus and discourse version just to check if this is still an issue?

**Comment by sideshowcoder** [comment] 2017-02-06 20:41
I can't reproduce this so I'm closing it for now maybe it got fixed in a recent version? Feel free to reopen if you are still experiencing this. Thank you :)

**Closed by sideshowcoder** 2017-02-06 20:41 UTC
