### ISSUE TITLE
Zeus causes wacky terminal formatting problems

### ISSUE THREAD

**Issue by petebrooks** [burke/zeus#510] opened 2015-03-03 17:26 UTC
Zeus seems to be affecting my terminal formatting (I'm using iTerm 2).
I've noticed problems with git:
```
On branch topic_model_and_controller_87982872
                                             Changes not staged for commit:
                                                                             (use "git add <file>..." to update what will be committed)
                         (use "git checkout -- <file>..." to discard changes in working directory)

                                                                                                  	modified:   spec/spec_helper.rb

                       no changes added to commit (use "git add" and/or "git commit -a")
```

And with RSpec formatting:
```
Run options: include {:focus=>true}

                                   All examples were filtered out; ignoring {:focus=>true}

                                                                                          Randomized with seed 27249

    TopicsController
                      #create
                                 routes to TopicsController#create
                                                                      conflicts
                                                                                     when both the title and tmnt_id are already in use
                               behaves like does not create and returns status
                                                                                        does not create the topic
           returns ok
                           when the title is already in use
                                                                   behaves like does not create and returns status
            does not create the topic
                                               returns conflict
```
This only happens when I'm running Zeus in another tab.  Opening a new tab fixes the problem, but that takes time and I lose my history.

Any idea why this might be happening?

**Comment by posgarou** [comment] 2015-03-14 17:57
I've noticed the same problem using Zeus 0.15.4, iTerm 2.0.0.20141103, and (if it's relevant) zsh 5.0.5.

It also seems to only affect some iTerm tabs and not others: one will get messed up formatting like @petebrooks described, while the other tabs will stay just fine.

**Comment by latortuga** [comment] 2015-03-25 15:09
Thanks for the report, this is a duplicate of #469 and there is a workaround provided there for the time being.

**Closed by latortuga** 2015-03-25 15:09 UTC
