### ISSUE TITLE
"Terminated: 15 " Running tests

### ISSUE THREAD

**Issue by jeremiahlukus** [burke/zeus#631] opened 2017-04-22 21:18 UTC
While running zeus rspec I get this error. If I run it again everything works fine. Half of the time it works normally. The other half I get Terminated: 15 then it works after running again.

**Comment by jeremiahlukus** [comment] 2017-04-22 22:44
Now it just randomly stopped working?

**Comment by laughinghan** [comment] 2017-04-24 18:04
Dupe of https://github.com/burke/zeus/issues/598

**Comment by sideshowcoder** [comment] 2017-05-19 08:19
As dupe of #598 going to close that.

**Closed by sideshowcoder** 2017-05-19 08:19 UTC
