### ISSUE TITLE
zeus v0.15.10: undefined method `invoke' for RSpec::Core::Runner::Class

### ISSUE THREAD

**Issue by NoICE** [burke/zeus#588] opened 2016-09-07 16:43 UTC
Just installed new zeus from rubygems and ran into this issue:

``` sh
$ zeus rspec spec/
/Users/noice/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/zeus-0.15.10/lib/zeus/rails.rb:207:in `test': undefined method `invoke' for RSpec::Core::Runner:Class (NoMethodError)
        from /Users/noice/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/zeus-0.15.10/lib/zeus.rb:147:in `block in command'
        from /Users/noice/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/zeus-0.15.10/lib/zeus.rb:134:in `fork'
        from /Users/noice/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/zeus-0.15.10/lib/zeus.rb:134:in `command'
        from /Users/noice/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/zeus-0.15.10/lib/zeus.rb:50:in `go'
        from -e:1:in `<main>'
```

Zeus itself starts just fine.

``` sh
ruby 2.0.0p598
$ bundle list|egrep "\* (rails|rake)"
  * rails (4.0.10)
  * rails-observers (0.1.2)
  * rake (10.4.2)
$ bundle list|grep rspec
  * guard-rspec (4.2.0)
  * rspec (2.14.1)
  * rspec-core (2.14.7)
  * rspec-expectations (2.14.4)
  * rspec-mocks (2.14.4)
  * rspec-rails (2.14.0)
```

Downgraded to my previously installed zeus 0.15.4 and that still works correctly.

**Comment by chip** [comment] 2016-09-08 21:24
I had a similar issue, but was running different versions:

```
$ rbenv local
2.2.5
 ...Macintosh HD 2/code/art-steps   master ✘ ✹ ✚ 
$ bundle list|egrep "\* (rails|rake)"
  * rails (3.2.13)
  * rails_12factor (0.0.3)
  * rails_serve_static_assets (0.0.5)
  * rails_stdout_logging (0.0.5)
  * rake (11.2.2)
 ...Macintosh HD 2/code/art-steps   master ✘ ✹ ✚ 
$ bundle list|grep rspec             
  * guard-rspec (4.7.3)
  * rspec (2.99.0)
  * rspec-collection_matchers (1.1.2)
  * rspec-core (2.99.2)
  * rspec-expectations (2.99.2)
  * rspec-mocks (2.99.4)
  * rspec-rails (2.99.0)
 ...Macintosh HD 2/code/art-steps   master ✘ ✹ ✚ 
$ zeus --version        
Zeus version 0.15.3
```

Downgrading to 0.15.3 worked for me.

**Comment by pavel-d** [comment] 2016-09-09 13:45
+1

**Comment by metcalf** [comment] 2016-09-16 17:46
@latortuga: It looks like this was a result of your change https://github.com/burke/zeus/pull/514/commits/954894af8c1d69af958860ea7f2bd2333283b91f in https://github.com/burke/zeus/pull/514. Can you investigate?

**Comment by latortuga** [comment] 2016-09-16 18:27
sigh yeah it probably is from that change. It really cleaned some things up. I wonder, if we were to add `require 'rspec/autorun'` like the minitest version, would that clean it up? hmm....

**Comment by bingxie** [comment] 2016-09-21 01:08
+1

**Comment by jeyraof** [comment] 2016-09-28 07:51
+1

**Comment by ianforsyth** [comment] 2016-10-08 01:26
+1

**Comment by thuanbuitinypulse** [comment] 2016-10-14 08:13
+1

**Comment by tw5475** [comment] 2016-11-08 06:32
+3

**Comment by richkettle** [comment] 2016-11-15 10:44
+1

**Comment by alexpinsky** [comment] 2016-11-23 10:53
+1

**Comment by excalq** [comment] 2016-11-28 19:50
Any update on this? I'm seeing it with zeus-0.15.10 running Rspec 2.14.8, with a Rails 3.2 app, running Ruby 2.1.5 (rbenv).

**Comment by dmahlow** [comment] 2016-12-06 12:57
It looks like the 'invoke' class method called in https://github.com/burke/zeus/pull/514/commits/954894af8c1d69af958860ea7f2bd2333283b91f is only available in rspec from version 3.0.0 forward: https://github.com/rspec/rspec-core/commit/0728973744e6463dd9701e0dfd2627f3c37d8367

So if you don't want to downgrade zeus, you can also try to upgrade rspec to ~> 3.0.0

**Comment by dmahlow** [comment] 2017-01-11 10:49
This still seems to be an issue with 0.15.12.

**Comment by sideshowcoder** [comment] 2017-01-11 11:30
So I guess the way to fix this is to check the RSpec version first and then do the right thing according to https://github.com/burke/zeus/pull/514/commits/954894af8c1d69af958860ea7f2bd2333283b91f

**Comment by sideshowcoder** [comment] 2017-01-15 20:34
Should be fixed now :)

**Closed by sideshowcoder** 2017-01-15 20:34 UTC

**Comment by dmahlow** [comment] 2017-01-24 16:14
Confirmed working in 0.15.13.pre. Thanks!
